<?php

$this->title = "Show project";
$this->headTitle($this->title);
?>

<h3 class="muted">Table list</h3>

<div class="row">
	<?php
		if (sizeof($this->paginator)):
	?>
   <div class="span12">
      <table class="table table-striped table-bordered table-hover">
         <thead>
            <tr>
               <th>Table name</th>
               <th width="40%">&nbsp;</th>
            </tr>
         </thead>
         <tbody>
         <?php foreach($this->paginator as $table): ?>
            <tr>
               <td><?=$this->escape($table) ?></td>
               <td>
                  <div class="btn-group">
                     <a href="<?=$this->url(array('controller' => 'projects',
                        'action' => 'form',
                        'table' => $this->escape($table))) ?>"
                        class="btn"><i class="icon-th-list"></i> Form</a>
                     <a href="<?=$this->url(array('controller' => 'projects',
                        'action' => 'model',
                        'table' => $this->escape($table))) ?>"
                        class="btn"><i class="icon-file"></i> Model</a>
                     <a href="#" class="btn"><i class="icon-eye-open"></i> View</a>
                     <a href="<?=$this->url(array('controller' => 'projects',
                        'action' => 'controller',
                        'table' => $this->escape($table))) ?>"
                        class="btn"><i class="icon-random"></i> Controller</a>
                  </div>
               </td>
            </tr>
         <?php endforeach; ?>
         </tbody>
      </table>
   </div>
	
	<div class="row">
		<div class="span12">
			<?php echo $this->paginator; ?>
		</div>
	</div>
	
	<?php
		else:
	?>
	<div class="alert alert-block">
		No projects found.
	</div>
	<?php
		endif;
	?>
</div>
