<?php
$this->headLink()->appendStylesheet($this->baseUrl() . '/lib/css/datatables/DT_bootstrap.css');

$this->headScript()->appendFile($this->baseUrl() . '/lib/js/datatables/jquery.dataTables.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/lib/js/datatables/DT_bootstrap.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/projects/show.js');

$this->title = "Show project";
$this->headTitle($this->title);
?>

<h3 class="muted">Table list</h3>

<div class="row">
    <?php if (sizeof($this->paginator)): ?>
        <div class="span12">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>Table name</th>
                        <th width="40%">&nbsp;</th>
                    </tr>
                </thead>
                <tbody>
                <?php foreach ($this->paginator as $item): ?>
                    <?php
                    $table_schema = $this->escape($item['table_schema']);
                    $table_name = $this->escape($item['table_name']);
                    ?>
                    <tr>
                        <td>
                            <?= $table_schema ?>.<?= $table_name ?>
                        </td>
                        <td>
                            <div class="btn-group">
                                <a href="<?=
                                $this->url(array('controller' => 'projects',
                                    'action' => 'form',
                                    'table' => $table_name,
                                    'schema' => $table_schema
                                ))
                                ?>"
                                   class="btn"><i class="icon-th-list"></i> Form</a>

                                <a href="<?=
                                $this->url(array('controller' => 'projects',
                                    'action' => 'model',
                                    'table' => $table_name,
                                    'schema' => $table_schema
                                ))
                                ?>"
                                   class="btn"><i class="icon-file"></i> Model</a>

                                <a href="<?=
                                $this->url(array('controller' => 'projects',
                                    'action' => 'view',
                                    'table' => $table_name,
                                    'schema' => $table_schema
                                ))
                                ?>"
                                   class="btn"><i class="icon-eye-open"></i> View</a>

                                <a href="<?=
                                $this->url(array('controller' => 'projects',
                                    'action' => 'controller',
                                    'table' => $table_name,
                                    'schema' => $table_schema
                                ))
                                ?>"
                                   class="btn"><i class="icon-random"></i> Controller</a>
                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>

    <?php else: ?>
    <div class="alert alert-block">
        No projects found.
    </div>
    <?php endif; ?>
</div>
