<?php

$this->title = "View";
$this->headTitle($this->title);
$this->back = $this->url(array('controller' => 'projects',
    'action' => 'show', 'id' => $this->id), 'default', true);
?>
<?php if ($this->code): ?>
<div class="row">
   <div class="span12">
      <pre class="prettyprint">
<?php
    $aux = str_replace("&lt;", "<", $this->code);
    $aux = str_replace("&gt;", ">", $aux);
?>
<?=$this->escape($aux) ?>
      </pre>
   </div>
</div>
<?php endif; ?>
