<?php
$this->title = "About";
$this->headTitle($this->title);
?>
<div class="row">
   <div class="span4">
      <div class="page-header">
         <h1>Yazte</h1><small>Yet Another Zend Template Engine</small>
      </div>
      <p>
         Yazte manage your projects as well generate files based on a template.
      </p>
      <p>
         This software is made using <a href="http://www.zend.com/">Zend Framework</a>.
      </p>
      <p>The layout is made using <a href="http://twitter.github.com/bootstrap/">Twitter Bootstrap</a>.</p>
      <p>
         Plugins:
      <ul>
         <!--li><a href="https://github.com/minddust/bootstrap-progressbar">bootstrap-progressbar</a></li-->
         <li><a href="http://twitter.github.com/bootstrap/javascript.html#tooltips">bootstrap-tooltip.js</a></li>
         <!--li><a href="https://github.com/akzhan/jwysiwyg">WYSIWYG jQuery Plugin - v0.8</a></li-->
      </ul>
      </p>
   </div>
   <div class="span4">
      <div class="page-header">
         <h1>Átila Camurça</h1><small>about me.</small>
      </div>
      <p>
         Developer and student of Computer Science. Work with Java, jQuery, PHP, Ruby.
      </p>
      <p> Find me at <a href="https://twitter.com/#!/atilacamurca">Twitter</a>
         or <a href="https://www.facebook.com/atilacamurca">Facebook</a>.</p>
   </div>
</div>
