<?php

/*echo $this->headScript()
      ->prependFile($this->baseUrl('js/index/index.js'),'text/javascript');*/

$this->title = "Projects";
$this->headTitle($this->title);
?>

<div class="row">
	<?php
		if (sizeof($this->paginator)):
	?>
	<ul class="thumbnails">
		<?php foreach($this->paginator as $project): ?>
	  <li class="span4">
		 <div class="thumbnail">
			<img src="img/250x150.gif" alt="" class="img-rounded">
			<h4><?=$this->escape($project['name']) ?></h4>
			<p><?=$this->escape($project['description']) ?></p>
			<div class="btn-group">
				<a href="<?=$this->url(array('controller' => 'projects',
					'action' => 'show')) ?>" class="btn">Show</a>
			</div>
		 </div>
	  </li>
	  <?php endforeach; ?>
	</ul>
	
	<div class="row">
		<div class="span9">
			<?php echo $this->paginator; ?>
			<div class="btn-group dropup">
					<a href="#" class="btn" rel="tooltip" title="Options">
						<i class="icon-cog"></i>
					</a>
					<button class="btn dropdown-toggle" data-toggle="dropdown">
						<span class="caret"></span>
					</button>
					<ul class="dropdown-menu">
						<li>
							<a href="<?= $this->url(array('show_hidden' => 1)) ?>">
								Show Hidden Projects</a>
						</li>
						<li>
							<a href="<?= $this->url(array('show_hidden' => 2)) ?>">
								Show Only Hidden</a>
						</li>
					</ul>
				</div>
		</div>
	</div>
	
	<?php
		else:
	?>
	<div class="alert alert-block">
		No projects found.
	</div>
	<?php
		endif;
	?>
</div>

<hr>

<div class="row">
   <div class="span12">
      <ul>
      <? foreach($this->tables  as $t): ?>
         <li><?=$t ?></li>
      <? endforeach; ?>
      </ul>
   </div>
</div>
